### PR TITLE
remove embed_widgets extension

### LINKED ISSUE #34: Remove embed_widgets extension
This is superseded by the the new machinery.

### PR DESCRIPTION
**Pull request by jbweston**
Superceded by jupyter_sphinx.execute.

Closes #34.

### CODE REVIEW

**Comment by akhmerov** [comment]
@SylvainCorlay do you agree?

**Comment by akhmerov** [comment]
Hm, this conflicts with #24, which uses some code from `embed_widgets`.

**Comment by jasongrout** [comment]
The widget cookiecutter needs to be updated to reflect this change: https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/0a0c36e021f2797c2d241abe9e23de8b3f00074c/%7B%7Bcookiecutter.github_project_name%7D%7D/docs/source/conf.py#L32

What should we use instead in the above line?

**Comment by akhmerov** [comment]
`jupyter_sphinx.execute` is the correct extension. How is this used in the cookiecutter?

**Pull request merged**
